export const firestoreCollections = {
  userProfiles: {
    name: "userProfiles",
    counterKey: "userProfiles",
    prefix: "USR-",
    padding: 6,
    idStrategy: "auth-uid",
    sequentialField: "userCode",
  },
  workshops: {
    name: "workshops",
    counterKey: "workshops",
    prefix: "TAL-",
    padding: 6,
    idStrategy: "sequential-doc-id",
  },
  workshopMemberships: {
    name: "workshopMemberships",
    counterKey: "workshopMemberships",
    prefix: "MEM-",
    padding: 6,
    idStrategy: "manual-doc-id",
  },
  staffInvitations: {
    name: "staffInvitations",
    counterKey: "staffInvitations",
    prefix: "INV-",
    padding: 6,
    idStrategy: "email-doc-id",
  },
  clients: {
    name: "clients",
    counterKey: "clients",
    prefix: "CLI-",
    padding: 6,
    idStrategy: "sequential-doc-id",
  },
  vehicles: {
    name: "vehicles",
    counterKey: "vehicles",
    prefix: "VEH-",
    padding: 6,
    idStrategy: "sequential-doc-id",
  },
  diagnostics: {
    name: "diagnostics",
    counterKey: "diagnostics",
    prefix: "DIA-",
    padding: 6,
    idStrategy: "sequential-doc-id",
  },
  workOrders: {
    name: "workOrders",
    counterKey: "workOrders",
    prefix: "ORD-",
    padding: 6,
    idStrategy: "sequential-doc-id",
  },
  progressEntries: {
    name: "progressEntries",
    counterKey: "progressEntries",
    prefix: "AVA-",
    padding: 6,
    idStrategy: "sequential-doc-id",
  },
  spareParts: {
    name: "spareParts",
    counterKey: "spareParts",
    prefix: "REP-",
    padding: 6,
    idStrategy: "sequential-doc-id",
  },
  stockItems: {
    name: "stockItems",
    counterKey: "stockItems",
    prefix: "STK-",
    padding: 6,
    idStrategy: "sequential-doc-id",
  },
};
