import {
  INVITATION_STATUSES,
  USER_ROLES,
  USER_STATUSES,
} from "./accessControl";

export const userProfileModel = {
  collection: "userProfiles",
  documentId: "firebase-auth-uid",
  visibleCodeField: "userCode",
  fields: [
    "uid",
    "userCode",
    "fullName",
    "email",
    "phone",
    "role",
    "status",
    "invitationId",
    "createdAt",
    "updatedAt",
    "lastLoginAt",
  ],
  defaults: {
    role: USER_ROLES.MECHANIC,
    status: USER_STATUSES.PENDING_APPROVAL,
  },
};

export const staffInvitationModel = {
  collection: "staffInvitations",
  documentId: "sequential",
  fields: [
    "id",
    "sequentialId",
    "email",
    "role",
    "status",
    "invitedByUid",
    "acceptedByUid",
    "expiresAt",
    "createdAt",
    "updatedAt",
  ],
  defaults: {
    status: INVITATION_STATUSES.PENDING,
  },
};

export const domainEntityModels = {
  clients: {
    collection: "clients",
    documentId: "sequential",
    fields: [
      "id",
      "sequentialId",
      "fullName",
      "address",
      "phone",
      "email",
      "notes",
      "createdByUid",
      "createdAt",
      "updatedAt",
    ],
  },
  vehicles: {
    collection: "vehicles",
    documentId: "sequential",
    fields: [
      "id",
      "sequentialId",
      "clientId",
      "plate",
      "brand",
      "model",
      "year",
      "color",
      "vin",
      "mileage",
      "notes",
      "createdAt",
      "updatedAt",
    ],
  },
  diagnostics: {
    collection: "diagnostics",
    documentId: "sequential",
    fields: [
      "id",
      "sequentialId",
      "vehicleId",
      "clientId",
      "openedByUid",
      "assignedMechanicUid",
      "status",
      "concerns",
      "serviceItems",
      "spareParts",
      "notes",
      "photos",
      "createdAt",
      "updatedAt",
    ],
  },
  workOrders: {
    collection: "workOrders",
    documentId: "sequential",
    fields: [
      "id",
      "sequentialId",
      "diagnosticId",
      "vehicleId",
      "clientId",
      "assignedMechanicUids",
      "status",
      "approvedAt",
      "startedAt",
      "finishedAt",
      "deliveredAt",
      "createdAt",
      "updatedAt",
    ],
  },
  progressEntries: {
    collection: "progressEntries",
    documentId: "sequential",
    fields: [
      "id",
      "sequentialId",
      "workOrderId",
      "diagnosticId",
      "vehicleId",
      "authorUid",
      "type",
      "message",
      "photos",
      "statusSnapshot",
      "createdAt",
      "updatedAt",
    ],
  },
  spareParts: {
    collection: "spareParts",
    documentId: "sequential",
    fields: [
      "id",
      "sequentialId",
      "diagnosticId",
      "workOrderId",
      "name",
      "quantity",
      "unitCost",
      "supplier",
      "status",
      "createdAt",
      "updatedAt",
    ],
  },
};
